regenerate json file for lcid
cyipt/actdev pull request #177
Opened 2021-07-09 14:51 UTC by natesheehan

Regenerated JSON file for active LCID - @dabreegster can you confirm this is looking okay?

2021-07-09 15:05 UTC, Robinlovelace requested changes
Heads-up @natesheehan I don't think this is ready to go yet, it's still using the old schema with origin associated with people not trip attributes:

![image](https://user-images.githubusercontent.com/1825120/125098959-6e669200-e0cf-11eb-9a32-ab28720ad58d.png)

2021-07-09 15:47 UTC, dabreegster commented
I realized I forgot about another breaking schema change on my end that's pretty important! We need to multiply `departure` by `10000.0` now too; there's a change in A/B Street serialization to compress floating point numbers. Could we also squeeze that in the `abstr` code and the test JSON file here?

2021-07-09 15:50 UTC, Robinlovelace commented
> Could we also squeeze that in the abstr code and the test JSON file here?

Absolutely but requires a fix upstream.

2021-07-11 11:21 UTC, natesheehan commented
https://github.com/cyipt/actdev/issues/178

2021-07-11 11:22 UTC, natesheehan commented
I have made the changes to the abstr-scenarios.r file - this afternoon I am going to rerun the build script for sites affected by #179

2021-07-11 22:56 UTC, Robinlovelace approved these changes
Great work @natesheehan this looks good to me.

2021-07-11 22:56 UTC, Robinlovelace commented on code/abstr-scenarios.R
> +od = desire_lines %>% rename(Walk = walk_base, Bike = cycle_base, Drive = drive_base)
:+1:

2021-07-11 22:56 UTC, Robinlovelace commented on code/abstr-scenarios.R
> +od_active = desire_lines %>% rename(Walk = walk_go_active, Bike = cycle_go_active, Drive = drive_go_active)
:+1: :+1:

2021-07-11 23:09 UTC, dabreegster commented
`scenario_base.json` imports just fine, and the departure times look correct:
![Screenshot from 2021-07-11 16-08-47](https://user-images.githubusercontent.com/1664407/125212450-60954600-e262-11eb-93ae-c45cd50deb9f.png)

2021-07-12 06:47 UTC, merged